# system file bootstrap is not supported on windows
# bootstrap hook does not respect 'shell' on windows
# mise also won't touch files outside the home dir using hooks directly - but invoking a script will work

# [bootstrap.files."C:/ProgramData/ssh/sshd_config"]
# content = '''
# AuthorizedKeysFile .ssh/authorized_keys
# PasswordAuthentication no
# PubkeyAuthentication yes
# '''

[bootstrap.hooks.final]
run = 'pwsh -c "& ~/.config/mise/conf.d/sshd.ps1"'

[bootstrap.packages]
"scoop:7zip" = "latest"
"scoop:aria2" = "latest"
"scoop:dark" = "latest"
"scoop:innounp" = "latest"
"scoop:lessmsi" = "latest"
"scoop:sudo" = "latest"
"scoop:pwsh" = "latest"

"scoop:adb" = "latest"
"scoop:dra" = "latest"
"scoop:driverstoreexplorer" = "latest"
"scoop:eza" = "latest"
"scoop:firacode-nf" = "latest"
"scoop:gh" = "latest"
"scoop:googlechrome" = "latest"
"scoop:grep" = "latest"
"scoop:mise" = "latest"
"scoop:mpv" = "latest"
"scoop:nano" = "latest"
"scoop:obsidian" = "latest"
"scoop:qview" = "latest"
"scoop:tldr" = "latest"
"scoop:uutils-coreutils" = "latest"
"scoop:vcredist2022" = "latest"
"scoop:which" = "latest"
"scoop:windowsdesktop-runtime-lts" = "latest"
"scoop:wiztree" = "latest"
"scoop:zed" = "latest"

"scoop:chris/a4dj" = "latest"
"scoop:chris/amesettings" = "latest"
#"scoop:chris/audiorelay" = "latest"
#"scoop:chris/docker" = "latest"
"scoop:chris/chplib" = "latest"
"scoop:chris/epatcher" = "latest"
"scoop:chris/everything" = "latest"
"scoop:chris/fcast" = "latest"
"scoop:chris/fpilot" = "latest"
"scoop:chris/git" = "latest"
"scoop:chris/hotkey" = "latest"
"scoop:chris/lnks" = "latest"
"scoop:chris/openshell" = "latest"
"scoop:chris/opgui_np" = "latest"
"scoop:chris/powertoys" = "latest"
"scoop:chris/portable" = "latest"
"scoop:chris/ssh" = "latest"
"scoop:chris/steinberg" = "latest"
"scoop:chris/uavolt" = "latest"
"scoop:chris/wt" = "latest"
"scoop:chris/zen_np" = "latest"