[env]
# fnox can't expand paths with ~ as home on windows, and tera templates can't expand ~ into C:/users/chris/
FNOX_AGE_KEY_FILE = "C:/users/chris/.ssh/id_ed25519"
FNOX_CONFIG_DIR = "C:/users/chris/.config/fnox"
MISE_AGE_KEY_FILE = "C:/users/chris/.ssh/id_ed25519"
STARSHIP_CONFIG = "C:/users/chris/.config/starship/starship.toml"