[env]
# starship won't expand "~/.config..." for some reason
STARSHIP_CONFIG = "/home/chris/.config/starship/starship.toml"
MISE_JOBS = 8

[tools]
semver = "latest"
jless = "latest"
dust = "latest"
bottom = "latest"
gh = "latest"
bat = "latest"
eza = "latest"
fd = "latest"
rg = "latest"
jq = "latest"
sd = "latest"
yq = "latest"
jqp = "latest"
yazi = "latest"
fzf = "latest"

op = "latest"
fnox = "latest"
starship = "latest"
zoxide = "latest"
zellij = "latest"
atuin = "latest"

just = "latest"
powershell = "latest"
television = "latest"
rclone = "latest"
aws-cli = "latest"
ruff = "latest"
shellcheck = "latest"
mr-boxington = "latest"
helm = "latest"

rust = "latest"
go = "latest"
zig = "latest"
zls = "latest"
lua = "latest"

bun = "latest"
node = "latest"
pnpm = "latest"
npm = "latest"

"cargo:tealdeer" = "latest"
"cargo:tokei" = "latest"
"cargo:dysk" = "latest"
"cargo:nu" = "latest"
"cargo:topgrade" = "latest"
"cargo:cargo-update" = "latest"
"cargo:cargo-binstall" = "latest"
"cargo:cargo-dist" = "latest"
