[tools]
"aqua:Canop/dysk" = { version = "latest", lazy = true }
bat = { version = "latest", lazy = true }
bottom = { version = "latest", lazy = true }
dust = { version = "latest", lazy = true }
eza = { version = "latest", lazy = true }
fd = { version = "latest", lazy = true }
fnox = { version = "latest", lazy = true }
gh = { version = "latest", lazy = true }
jq = { version = "latest", lazy = true }
just = { version = "latest", lazy = true }
op = { version = "latest", lazy = true }
rg = { version = "latest", lazy = true }
sd = { version = "latest", lazy = true }
starship = { version = "latest", lazy = true }
television = { version = "latest", lazy = true }
yazi = { version = "latest", lazy = true }
yq = { version = "latest", lazy = true }
zellij = { version = "latest", lazy = true }
zoxide = { version = "latest", lazy = true }