[tools]
semver = { version = "latest", os = ["linux"] }
jless = { version = "latest", os = ["linux"] }
dust = "latest"
bottom = "latest"
gh = "latest"
bat = "latest"
eza = "latest"
fd = "latest"
rg = "latest"
jq = "latest"
sd = "latest"
yq = "latest"
jqp = "latest"
yazi = "latest"
fzf = "latest"

op = "latest"
fnox = "latest"
starship = "latest"
zoxide = "latest"
zellij = "latest"
atuin = "latest"

just = { version = "latest", os = ["linux"] }
powershell = { version = "latest", os = ["linux"] }
television = { version = "latest", os = ["linux"] }
rclone = { version = "latest", os = ["linux"] }
aws-cli = { version = "latest", os = ["linux"] }
ruff = { version = "latest", os = ["linux"] }
shellcheck = { version = "latest", os = ["linux"] }
mr-boxington = { version = "latest", os = ["linux"] }
helm = { version = "latest", os = ["linux"] }

rust = { version = "latest", os = ["linux"] }
go = { version = "latest", os = ["linux"] }
zig = { version = "latest", os = ["linux"] }
zls = { version = "latest", os = ["linux"] }
lua = { version = "latest", os = ["linux"] }

bun = "latest"
node = { version = "latest", os = ["linux"] }
pnpm = { version = "latest", os = ["linux"] }
npm = { version = "latest", os = ["linux"] }

"cargo:tealdeer" = { version = "latest", os = ["linux"] }
"cargo:tokei" = { version = "latest", os = ["linux"] }
"cargo:dysk" = { version = "latest", os = ["linux"] }
"cargo:nu" = { version = "latest", os = ["linux"] }
"cargo:topgrade" = { version = "latest", os = ["linux"] }
"cargo:cargo-update" = { version = "latest", os = ["linux"] }
"cargo:cargo-binstall" = { version = "latest", os = ["linux"] }
"cargo:cargo-dist" = { version = "latest", os = ["linux"] }