[settings]
dotfiles.root = "~/Projects/bootstrap/home"
dotfiles.default_mode = "copy"

[history.encryption]
recipients = [
  "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBDbuPSH93RCTHG7iTHxg+De/yMWUVB+Q4EFt4llpPDL",
]

[bootstrap.repos]
"~/Projects/bootstrap" = { url = "git@github.com:chrishenn/bootstrap.git" }

[dotfiles]
"~/.bash_aliases" = {}
"~/.bashrc" = { mode = "copy", variants = [{ os = "linux" }] }
"~/.config/Code/User" = {}
"~/.config/Kvantum" = {}
"~/.config/Proton" = {}
"~/.config/atuin/config.toml" = {}
"~/.config/bottom/bottom.toml" = {}
"~/.config/dolphinrc" = {}
"~/.config/ghostty" = {}
"~/.config/glab-cli" = {}
"~/.config/input-remapper-2" = {}
"~/.config/mbx/config.toml" = {}
"~/.config/mise/config.toml" = {}
"~/.config/no-show-user-motd" = {}
"~/.config/nushell/config.nu" = {}
"~/.config/soar" = {}
"~/.config/starship/starship.toml" = {}
"~/.config/tealdeer/config.toml" = {}
"~/.config/topgrade/topgrade.toml" = {}
"~/.config/wezterm/wezterm.lua" = {}
"~/.config/zed/settings.json" = {}
"~/.config/zellij/config.kdl" = {}
"~/.gitconfig" = { source = "~/Projects/bootstrap/home/.gitconfig.tera", mode = "template" }
"~/.hushlogin" = {}
"~/.local/share/color-schemes/UtterlySweet.colors" = {}
"~/.local/share/custom_icons" = {}
"~/.local/share/easyeffects/autoload/output/mydefault.txt" = {}
"~/.local/share/konsole/Profile 1.profile" = {}
"~/.local/share/konsole/Utterly-Sweet-Konsole.colorscheme" = {}
"~/.local/share/plasma-systemmonitor" = {}
"~/.local/share/wallpapers/back.png" = {}
"~/.nanorc" = {}
"~/.profile" = {}
"~/.yt-dlp/config" = {}
"~/.zprofile" = {}
"~/.zshrc" = {}
"~/gclone.sh" = {}
"~/justfile" = {}

"~/.ssh/authorized_keys" = { source = "~/Projects/bootstrap/home/.ssh/authorized_keys.tera", mode = "template" }
"~/.ssh/id_ed25519.pub" = { source = "~/Projects/bootstrap/home/.ssh/id_ed25519.pub.tera", mode = "template" }
"~/.ssh/id_ed25519" = { source = "~/Projects/bootstrap/home/.ssh/id_ed25519.tera", mode = "template" }
"~/.ssh/known_hosts" = { source = "~/Projects/bootstrap/home/.ssh/known_hosts.tera", mode = "template" }

[dotfiles.scoop]
source = "~/Projects/bootstrap/home/.config/scoop/config.json"
mode = "template"
variants = [
    { os = "windows", target = "~/.config/scoop/config.json" },
]

[dotfiles.pwsh]
source = "$DOT/Documents/PowerShell/Microsoft.PowerShell_profile.ps1"
variants = [
    { os = "windows", target = "~/Documents/PowerShell/Microsoft.PowerShell_profile.ps1" },
]

[dotfiles.fnox]
# todo: try this now that we used $HOME instead of ~
# fnox does not respect FNOX_CONFIG_DIR on windows
source = "{{vars.dot}}/.config/fnox/config.toml"
variants = [
  { os = "linux", target = "~/.config/fnox/config.toml" },
  { os = "windows", target = "~/AppData/Local/fnox/config.toml" },
]

[dotfiles.mpv]
source = "~/Projects/bootstrap/home/.config/mpv/mpv.conf"
variants = [
  { os = "linux", target = "~/.config/mpv/mpv.conf" },
  { os = "windows", target = "~/AppData/Roaming/mpv/mpv.conf" },
]

[dotfiles.gh]
source = "~/Projects/bootstrap/home/.config/gh"
variants = [
  { os = "linux", target = "~/.config/gh" },
  { os = "windows", target = "~/AppData/Roaming/Github CLI/" },
]
