[settings]
experimental = true
registry_floating = true
auto_update = true
trusted_config_paths = ["/"]

dotfiles.root = "~/Projects/bootstrap/home"
dotfiles.default_mode = "copy"

[env]
FNOX_AGE_KEY_FILE = "$HOME/.ssh/id_ed25519"
FNOX_CONFIG_DIR = "$HOME/.config/fnox"
MISE_AGE_KEY_FILE = "$HOME/.ssh/id_ed25519"
STARSHIP_CONFIG = "$HOME/.config/starship/starship.toml"

TERM = "xterm-256color"
EDITOR = "nano"
KUBE_EDITOR = "nano"
COMPOSE_BAKE = true
OP_RUN_NO_MASKING = true

HK_MISE = 1
UV_PREVIEW = 1
JUST_UNSTABLE = 1

[tools]
semver = { version = "latest", os = ["linux"] }
jless = { version = "latest", os = ["linux"] }
dust = "latest"
bottom = "latest"
gh = "latest"
bat = "latest"
eza = "latest"
fd = "latest"
rg = "latest"
jq = "latest"
sd = "latest"
yq = "latest"
jqp = "latest"
yazi = "latest"
fzf = "latest"

op = "latest"
fnox = "latest"
starship = "latest"
zoxide = "latest"
zellij = "latest"
atuin = "latest"

just = { version = "latest", os = ["linux"] }
powershell = { version = "latest", os = ["linux"] }
television = { version = "latest", os = ["linux"] }
rclone = { version = "latest", os = ["linux"] }
aws-cli = { version = "latest", os = ["linux"] }
ruff = { version = "latest", os = ["linux"] }
shellcheck = { version = "latest", os = ["linux"] }
mr-boxington = { version = "latest", os = ["linux"] }
helm = { version = "latest", os = ["linux"] }

rust = { version = "latest", os = ["linux"] }
go = { version = "latest", os = ["linux"] }
zig = { version = "latest", os = ["linux"] }
zls = { version = "latest", os = ["linux"] }
lua = { version = "latest", os = ["linux"] }

bun = "latest"
node = { version = "latest", os = ["linux"] }
pnpm = { version = "latest", os = ["linux"] }
npm = { version = "latest", os = ["linux"] }

"cargo:tealdeer" = { version = "latest", os = ["linux"] }
"cargo:tokei" = { version = "latest", os = ["linux"] }
"cargo:dysk" = { version = "latest", os = ["linux"] }
"cargo:nu" = { version = "latest", os = ["linux"] }
"cargo:topgrade" = { version = "latest", os = ["linux"] }
"cargo:cargo-update" = { version = "latest", os = ["linux"] }
"cargo:cargo-binstall" = { version = "latest", os = ["linux"] }
"cargo:cargo-dist" = { version = "latest", os = ["linux"] }